# Generated by Django 3.0.8 on 2020-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='book_id')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('host', models.CharField(max_length=50, verbose_name='host')),
                ('link', models.CharField(max_length=200, verbose_name='link')),
                ('rate_summary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='rate_summary')),
            ],
        ),
        migrations.CreateModel(
            name='DataSourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
            ],
        ),
    ]
