# Generated by Django 3.0.8 on 2020-07-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_books_datasourse'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
