# Generated by Django 3.0.8 on 2020-07-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20200709_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSourse',
            new_name='DataSource',
        ),
    ]
