# Generated by Django 3.0.8 on 2020-07-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20200709_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.CharField(default=None, max_length=20, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='books',
            name='size',
            field=models.CharField(default=None, max_length=20, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.CharField(default='others', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='books',
            name='host',
            field=models.CharField(max_length=80, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
